export const contentData = {
  en: {
    siteName: '24x7 Indian News',
    tagline: 'Your Trusted Source for 24x7 News from India & the World',
    categories: {
      all: 'All News',
      indian: 'India',
      global: 'World',
      regional: 'Regional',
      politics: 'Politics',
      economy: 'Economy',
      sports: 'Sports',
      entertainment: 'Entertainment',
      technology: 'Tech',
      science: 'Science',
      health: 'Health',
      travel: 'Travel',
      opinion: 'Opinion',
      video: 'Video',
      auto: 'Auto',
      recipes: 'Recipes',
      beauty: 'Skincare & Beauty',
      lifestyle: 'Lifestyle',
      'jobs-education': 'Jobs & Education',
      'personal-finance': 'Personal Finance',
      'astrology-spiritual': 'Astrology & Spiritual',
      agriculture: 'Agriculture & Rural',
      'crime-law': 'Crime & Law',
      weather: 'Weather',
      'fact-check': 'Fact Check',
    },
    trending: 'Trending Now',
    breaking: 'Breaking News',
    latest: 'Latest Stories',
    subscribe: 'Subscribe for Updates',
    subscribeDesc: 'Get the latest news & top headlines delivered straight to your inbox. We respect your privacy.',
    emailPlaceholder: 'Enter your email address',
    subscribeBtn: 'Subscribe',
    subscribeSuccessTitle: 'Subscription Confirmed! 🎉',
    subscribeSuccessDesc: 'You\'re all set! Welcome to 24x7 Indian News updates.',
    subscribeErrorTitle: 'Subscription Failed',
    subscribeErrorDesc: 'An error occurred. Please check your email or try again later.',
    readMore: 'Read Full Story',
    shareArticle: 'Share',
    bookmark: 'Save Article',
    comments: 'Join Discussion',
    views: 'Views',
    minutesAgo: 'min ago',
    hoursAgo: 'hr ago',
    noNews: 'No Articles Available',
    noNewsDesc: 'We are working on bringing you the latest updates. Please check back soon!',
    moreNewsTitle: 'Explore More News',
    searchPlaceholder: 'Search 24x7 Indian News...',
    toggleLanguage: 'भाषा बदलें (Switch to Hindi)',
    toggleTheme: 'Toggle Dark/Light Mode',
    toggleMenu: 'Toggle Navigation Menu',
    articlePublished: 'Published on:',
    articleAuthor: 'By',
    relatedArticles: 'You Might Also Like',
    closeModal: 'Close Article View',
    fetchErrorTitle: 'Error Loading News',
    fetchErrorDesc: 'Could not fetch the latest articles. Please ensure you are connected to the internet.',
    networkErrorTitle: 'Network Connectivity Issue',
    networkErrorDesc: 'Unable to connect to the news server. Please check your internet connection and try again.',
    languageChangedTitle: 'Language Switched to English',
    languageChangedDesc: 'You are now viewing content in English.',
    darkModeEnabled: 'Dark Mode Activated',
    lightModeEnabled: 'Light Mode Activated',
    notAvailable: 'N/A',
    footer: {
      about: 'About 24x7 Indian News',
      contact: 'Contact Us',
      privacy: 'Privacy Policy',
      terms: 'Terms & Conditions',
      copyright: '© COPYRIGHT',
    },
    uploader: {
      openUploader: 'Upload New Article',
      title: 'Article Uploader',
      editTitle: 'Edit Article',
      description: 'Upload a .docx file to automatically convert it to a web article. Images will be extracted and uploaded.',
      uploadLabel: 'Upload .docx file',
      processing: 'Processing...',
      uploadSuccess: 'Article uploaded successfully!',
      uploadError: 'Failed to upload article.',
      form: {
        titleEn: 'Title (English)',
        titleHi: 'Title (Hindi)',
        excerptEn: 'Excerpt (English)',
        excerptHi: 'Excerpt (Hindi)',
        category: 'Category',
        selectCategory: 'Select a category',
        content: 'Article Content (HTML)',
        save: 'Save & Publish Article',
        saving: 'Saving...',
        featuredImage: 'Featured Image URL',
        cancel: 'Cancel',
      }
    }
  },
  hi: {
    siteName: '24x7 इंडियन न्यूज',
    tagline: 'भारत और दुनिया की 24x7 ख़बरों का आपका विश्वसनीय स्रोत',
    categories: {
      all: 'सभी समाचार',
      indian: 'भारत',
      global: 'विश्व',
      regional: 'क्षेत्रीय',
      politics: 'राजनीति',
      economy: 'अर्थव्यवस्था',
      sports: 'खेल',
      entertainment: 'मनोरंजन',
      technology: 'टेक्नोलॉजी',
      science: 'विज्ञान',
      health: 'स्वास्थ्य',
      travel: 'यात्रा',
      opinion: 'राय',
      video: 'वीडियो',
      auto: 'ऑटो',
      recipes: 'खाना खज़ाना',
      beauty: 'स्किनकेयर/ब्यूटी',
      lifestyle: 'लाइफस्टाइल',
      'jobs-education': 'नौकरी/शिक्षा',
      'personal-finance': 'पर्सनल फाइनेंस',
      'astrology-spiritual': 'राशिफल/धर्म',
      agriculture: 'कृषि/ग्रामीण',
      'crime-law': 'अपराध/कानून',
      weather: 'मौसम',
      'fact-check': 'फैक्ट चेक',
    },
    trending: 'अभी चर्चित',
    breaking: 'ब्रेकिंग न्यूज़',
    latest: 'नवीनतम समाचार',
    subscribe: 'अपडेट्स के लिए सब्सक्राइब करें',
    subscribeDesc: 'नवीनतम समाचार और मुख्य सुर्खियाँ सीधे अपने इनबॉक्स में पाएं। हम आपकी गोपनीयता का सम्मान करते हैं।',
    emailPlaceholder: 'अपना ईमेल पता दर्ज करें',
    subscribeBtn: 'सब्सक्राइब करें',
    subscribeSuccessTitle: 'सदस्यता की पुष्टि हुई! 🎉',
    subscribeSuccessDesc: 'आप पूरी तरह तैयार हैं! 24x7 Indian News अपडेट्स में आपका स्वागत है।',
    subscribeErrorTitle: 'सदस्यता विफल',
    subscribeErrorDesc: 'एक त्रुटि हुई। कृपया अपना ईमेल जांचें या बाद में पुनः प्रयास करें।',
    readMore: 'पूरी ख़बर पढ़ें',
    shareArticle: 'शेयर करें',
    bookmark: 'लेख सहेजें',
    comments: 'चर्चा में शामिल हों',
    views: 'बार देखा गया',
    minutesAgo: 'मिनट पहले',
    hoursAgo: 'घंटे पहले',
    noNews: 'कोई लेख उपलब्ध नहीं है',
    noNewsDesc: 'हम आपको नवीनतम अपडेट लाने पर काम कर रहे हैं। कृपया जल्द ही वापस देखें!',
    moreNewsTitle: 'और समाचार देखें',
    searchPlaceholder: '24x7 Indian News में खोजें...',
    toggleLanguage: 'Switch to English (अंग्रेजी में बदलें)',
    toggleTheme: 'डार्क/लाइट मोड बदलें',
    toggleMenu: 'नेविगेशन मेनू बदलें',
    articlePublished: 'प्रकाशित:',
    articleAuthor: 'द्वारा',
    relatedArticles: 'आपको यह भी पसंद आ सकता है',
    closeModal: 'लेख दृश्य बंद करें',
    fetchErrorTitle: 'समाचार लोड करने में त्रुटि',
    fetchErrorDesc: 'नवीनतम लेख प्राप्त नहीं किए जा सके। कृपया सुनिश्चित करें कि आप इंटरनेट से जुड़े हैं।',
    networkErrorTitle: 'नेटवर्क कनेक्टिविटी समस्या',
    networkErrorDesc: 'समाचार सर्वर से कनेक्ट करने में असमर्थ। कृपया अपना इंटरनेट कनेक्शन जांचें और पुनः प्रयास करें।',
    languageChangedTitle: 'भाषा हिंदी में बदल दी गई है',
    languageChangedDesc: 'अब आप सामग्री हिंदी में देख रहे हैं।',
    darkModeEnabled: 'डार्क मोड सक्रिय',
    lightModeEnabled: 'लाइट मोड सक्रिय',
    notAvailable: 'उपलब्ध नहीं',
    footer: {
      about: '24x7 Indian News के बारे में',
      contact: 'हमसे संपर्क करें',
      privacy: 'गोपनीयता नीति',
      terms: 'नियम एवं शर्तें',
      copyright: '© कॉपीराइट',
    },
    uploader: {
      openUploader: 'नया लेख अपलोड करें',
      title: 'लेख अपलोडर',
      editTitle: 'लेख संपादित करें',
      description: '.docx फ़ाइल अपलोड करें ताकि यह स्वचालित रूप से एक वेब लेख में परिवर्तित हो जाए। छवियाँ निकाली और अपलोड की जाएंगी।',
      uploadLabel: '.docx फ़ाइल अपलोड करें',
      processing: 'प्रोसेस हो रहा है...',
      uploadSuccess: 'लेख सफलतापूर्वक अपलोड हो गया!',
      uploadError: 'लेख अपलोड करने में विफल।',
      form: {
        titleEn: 'शीर्षक (अंग्रेजी)',
        titleHi: 'शीर्षक (हिंदी)',
        excerptEn: 'अंश (अंग्रेजी)',
        excerptHi: 'अंश (हिंदी)',
        category: 'श्रेणी',
        selectCategory: 'एक श्रेणी चुनें',
        content: 'लेख सामग्री (HTML)',
        save: 'सहेजें और प्रकाशित करें',
        saving: 'सहेज रहा है...',
        featuredImage: 'फीचर्ड इमेज यूआरएल',
        cancel: 'रद्द करें',
      }
    }
  }
};

export const mockNewsData = {
  breaking: [
    {
      id: 'mock-breaking-1',
      title_en: 'Market Hits Record High Amidst Global Optimism',
      title_hi: 'वैश्विक आशावाद के बीच बाजार रिकॉर्ड ऊंचाई पर पहुंचा',
      excerpt_en: 'Investors cheer as key indices surge, driven by positive economic indicators.',
      excerpt_hi: 'सकारात्मक आर्थिक संकेतकों से प्रेरित होकर प्रमुख सूचकांकों में तेजी आने से निवेशक उत्साहित हैं।',
      category: 'economy', time_ago: '5', views: 18200, is_breaking: true,
      image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3'
    }
  ],
  featured: [
    {
      id: 'mock-featured-1',
      title_en: 'Groundbreaking AI Discovers New Paths for Medical Research',
      title_hi: 'अभिनव एआई ने चिकित्सा अनुसंधान के लिए नए रास्ते खोजे',
      excerpt_en: 'A novel artificial intelligence model is accelerating drug discovery and personalizing treatments.',
      excerpt_hi: 'एक नया कृत्रिम बुद्धिमत्ता मॉडल दवा खोज को गति दे रहा है और उपचारों को वैयक्तिकृत कर रहा है।',
      category: 'technology', time_ago: '30', views: 25000, is_featured: true,
      content_en: 'Detailed content about AI in medical research...',
      content_hi: 'चिकित्सा अनुसंधान में एआई के बारे में विस्तृत सामग्री...',
      image_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69'
    }
  ],
  more: [
    {
      id: 'mock-more-1',
      title_en: 'Cultural Festival Draws Thousands to City Center',
      title_hi: 'सांस्कृतिक उत्सव ने हजारों लोगों को शहर के केंद्र की ओर आकर्षित किया',
      excerpt_en: 'A vibrant celebration of art, music, and tradition captivated attendees over the weekend.',
      excerpt_hi: 'कला, संगीत और परंपरा के एक जीवंत उत्सव ने सप्ताहांत में उपस्थित लोगों को मंत्रमुग्ध कर दिया।',
      category: 'entertainment', time_ago: '120', views: 7500,
      image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819'
    },
    {
      id: 'mock-more-2',
      title_en: 'Government Unveils New Green Energy Initiative',
      title_hi: 'सरकार ने नई हरित ऊर्जा पहल का अनावरण किया',
      excerpt_en: 'The plan aims to significantly increase renewable energy production by 2030.',
      excerpt_hi: 'इस योजना का लक्ष्य 2030 तक नवीकरणीय ऊर्जा उत्पादन में उल्लेखनीय वृद्धि करना है।',
      category: 'politics', time_ago: '240', views: 6800,
      image_url: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7'
    }
  ],
  trending: [
    { name_en: 'Quantum Computing Race', name_hi: 'क्वांटम कंप्यूटिंग की दौड़' },
    { name_en: 'Sustainable Fashion Trends', name_hi: 'सस्टेनेबल फैशन ट्रेंड्स' },
    { name_en: 'Space Tourism Next Steps', name_hi: 'अंतरिक्ष पर्यटन के अगले कदम' },
  ],
   regional: [
    { id: 'reg-1', state_en: 'Maharashtra', state_hi: 'महाराष्ट्र', news_en: 'Mumbai Metro expansion phase 3 approved.', news_hi: 'मुंबई मेट्रो विस्तार चरण 3 को मंजूरी।', category: 'regional' },
    { id: 'reg-2', state_en: 'Uttar Pradesh', state_hi: 'उत्तर प्रदेश', news_en: 'New film city project announced in Noida.', news_hi: 'नोएडा में नई फिल्म सिटी परियोजना की घोषणा।', category: 'regional' },
  ]
};
